
<footer class="mt-4">     
         <div id="redes"> 
                <a href="https://www.facebook.com"><img src="imagenes/facebook.png" width="50px"/></a>                 
                <a href="https://twitter.com/?lang=es"><img src="imagenes/twiter.png" width="50px"/></a>   
                       
                <a href="https://www.instagram.com/?hl=es"><img src="imagenes/instagram.png" width="50px"/></a>
        </div>

        <div class="footer-copyright text-center py-3">
          <a href="https://mdbootstrap.com/education/bootstrap/"> Despliegue.com</a>
          <br>
          <p class="copy text-center py-3">Derechos reservados por copyrigth - 2019 © </p>
        </div>
</footer>

</div>
</body>
</html>